feat(storage): provide implementation for badgerdb as profiles storage
getsentry/vroom pull request #199
Opened 2023-03-11 06:45 UTC by aldy505

Closes #188 

Tests on `storageprovider` package already handled and covered by `storageutils` package. I think there's no need to do the same test on `storageprovider`. But, if you think it'd be better to put additional tests on `storageprovider`, I'll be okay to write it.

I don't want to support AWS S3 and Azure yet, file storage is fine right now (and far lot cheaper than purchasing separate storage instance for storing profiles data).

2023-03-14 04:36 UTC, aldy505 commented
I don't know why the CI is failing at golang-ci lint. Found this thread https://github.com/golangci/golangci-lint/discussions/1920, said I must do `go clean -modcache && go mod tidy`. It doesn't change anything though :/

2023-03-14 10:16 UTC, viglia commented
Hey @aldy505 , for a better experience, I recommend installing the `pre-commit` hooks (see the readme) so that you can catch those kind of errors before the CI checks.

It seems what's happening here is that an "import cycle" between `storageutil` and `storageprovider` was introduced: `import cycle not allowed in test`

2023-03-14 23:32 UTC, aldy505 commented
I've installed pre-commit, but I don't know why it doesn't work on me. Anyway, thanks for the error message. I'll fix the issue later this weekend.

2023-03-15 09:31 UTC, viglia commented
> I've installed pre-commit, but I don't know why it doesn't work on me. Anyway, thanks for the error message. I'll fix the issue later this weekend.

@aldy505 After you've installed `pre-commit`, you also need to install the git hook scripts.
I'll fix the doc to add that step as it's missing. Meanwhile you can do that with `pre-commit install`.

With that in place the pre-commit hooks will run each time you commit something.

If you want to manually run the hooks regardless of whether you're committing something or not you can do that with `pre-commit run --all-files`.

2023-03-16 16:03 UTC, phacops commented
@aldy505 This is not the direction I want this layer to go towards. I'd rather reuse existing libraries like https://gocloud.dev/howto/blob/ which includes all major cloud providers and a local filesystem option in one package already.

Also, I don't think we'd target support for BadgerDB right now. We need to read and write files on a persistent medium and the filesystem is very well adapted to that for a local option, we don't need an embedded database for that right now.

2023-03-19 03:56 UTC, aldy505 commented
@phacops I've updated it to use gocloud instead.

2023-03-28 16:45 UTC, phacops requested changes
Thanks again for the contribution. I think it mostly looks good. I'd like you to improve the tests to repeat the code less.

If you look at https://github.com/getsentry/vroom/blob/main/internal/sample/sample_test.go#L14, we define a `struct` containing some data and then apply the same test code for each case. You could follow the same structure to repeat tests on all URLs instead of copy/pasting for each one.

Also, I'm not against launching a `fakestorage` server for the tests only but then you need to remove the one we launch via `docker-compose`.

2023-03-28 16:45 UTC, phacops commented on internal/storageutil/storageutil.go
> +	ow, err := b.NewWriter(ctx, objectName, &blob.WriterOptions{})
Was passing `nil` instead of a pointer to an empty `struct` not an option?

2023-03-28 16:45 UTC, phacops commented on internal/storageutil/storageutil_test.go
> +func TestDownloadProfile_NotFound(t *testing.T) {
Can you remove the `_` please?

2023-03-28 23:52 UTC, aldy505 commented
Also, I'm not against launching afakestorageserver for the tests only but then you need to remove the one we launch viadocker-compose.

@phacops the fakestorage server was there before I opened this PR 🫤

Other than that, I'll do the changes later this weekend.

Sent from Proton Mail for iOS

On Tue, Mar 28, 2023 at 23:46, Pierre Massat ***@***.***> wrote:

> @phacops requested changes on this pull request.
>
> Thanks again for the contribution. I think it mostly looks good. I'd like you to improve the tests to repeat the code less.
>
> If you look at https://github.com/getsentry/vroom/blob/main/internal/sample/sample_test.go#L14, we define a struct containing some data and then apply the same test code for each case. You could follow the same structure to repeat tests on all URLs instead of copy/pasting for each one.
>
> Also, I'm not against launching a fakestorage server for the tests only but then you need to remove the one we launch via docker-compose.
>
> ---------------------------------------------------------------
>
> In [cmd/vroom/config.go](https://github.com/getsentry/vroom/pull/199#discussion_r1150886369):
>
>> @@ -14,7 +14,8 @@ type (
>		CallTreesKafkaTopic   string   `env:"SENTRY_KAFKA_TOPIC_CALL_TREES" env-default:"profiles-call-tree"`
>		ProfilesKafkaTopic    string   `env:"SENTRY_KAKFA_TOPIC_PROFILES" env-default:"processed-profiles"`
>
> -		ProfilesBucket string `env:"SENTRY_GCS_BUCKET_PROFILES" env-default:"sentry-profiles"`
> -		SnubaHost      string `env:"SENTRY_SNUBA_HOST" env-default:"http://localhost:1218"`
> +		SnubaHost string `env:"SENTRY_SNUBA_HOST" env-default:"http://localhost:1218"`
> +
> +		BucketURLString string `env:"SENTRY_BUCKET_PROFILES" env-default:"file://localhost/var/lib/sentry-profiles"`
>
> Can you remove the String suffix please?
>
> ---------------------------------------------------------------
>
> In [internal/storageutil/storageutil.go](https://github.com/getsentry/vroom/pull/199#discussion_r1150888277):
>
>>	ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
>	defer cancel()
>
> -	ow := b.Object(objectName).NewWriter(ctx)
> +	ow, err := b.NewWriter(ctx, objectName, &blob.WriterOptions{})
>
> Was passing nil instead of a pointer to an empty struct not an option?
>
> ---------------------------------------------------------------
>
> In [cmd/vroom/main.go](https://github.com/getsentry/vroom/pull/199#discussion_r1150891118):
>
>> @@ -58,10 +61,12 @@ func newEnvironment() (*environment, error) {
>		return nil, err
>	}
>	ctx := context.Background()
> -	e.storage, err = storage.NewClient(ctx)
> +
> +	e.storage, err = blob.OpenBucket(context.Background(), e.config.BucketURLString)
>
> Please use the ctx variable defined right above.
>
> ---------------------------------------------------------------
>
> In [internal/storageutil/storageutil_test.go](https://github.com/getsentry/vroom/pull/199#discussion_r1150891723):
>
>> +		err = UnmarshalCompressed(ctx, fileBlobBucket, objectName, &profile)
> +		if err != nil {
> +			t.Fatalf("we should be able to read the object: %v", err)
> +		}
> +
> +		uncompressedData, err := json.Marshal(profile)
> +		if err != nil {
> +			t.Fatalf("we should be able to marshal back to JSON: %v", err)
> +		}
> +		if !bytes.Equal(originalData, uncompressedData) {
> +			t.Fatalf("data should be identical: %v %v", string(originalData), string(uncompressedData))
> +		}
> +	})
> +}
> +
> +func TestDownloadProfile_NotFound(t *testing.T) {
>
> Can you remove the _ please?
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/getsentry/vroom/pull/199#pullrequestreview-1361508260), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/ABXP6VW6U56QMEKWAEVMO5DW6MIU7ANCNFSM6AAAAAAVXJ7ZRU).
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-03-30 22:35 UTC, phacops commented
You're right, I set it up that way so we don't have to run `docker-compose` and an additional Docker contain in the tests. I forgot about that.

Then just remove the `docker-compose` config from the repo since we don't need it anymore to run the development environment (we're using the filesystem now).

2023-04-04 23:16 UTC, phacops approved these changes

2023-04-04 23:20 UTC, phacops requested changes
You need to also get rid of the `docker-compose` invocation in `scripts/run.sh` if you're going to remove the `docker-compose.yml` file.

2023-04-06 19:07 UTC, phacops approved these changes

2023-04-06 19:07 UTC, merged