Use debian bullseye in DockerFile
getsentry/vroom pull request #290
Opened 2023-07-17 17:26 UTC by hubertdeng123

2023-07-17 22:15 UTC, aldy505 commented on Dockerfile
> +FROM debian:bullseye-slim
Bookworm is the latest stable now. Shouldn't we use that instead?

2023-07-17 23:45 UTC, hubertdeng123 commented on Dockerfile
> +FROM debian:bullseye-slim
the reason why I'm using bullseye is because symbolicator and sentry are both using that, so that's what I would prefer

2023-07-18 13:29 UTC, phacops requested changes

2023-07-18 13:29 UTC, phacops commented on Dockerfile
> +RUN apt-get update && apt-get install -y ca-certificates tzdata && \
I suggest we add an `apt-get clean` and `--no-install-recommends` as well:
```suggestion
RUN apt-get update \
    && apt-get install -y ca-certificates tzdata --no-install-recommends \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p $PROFILES_DIR
```

2023-07-18 13:29 UTC, phacops commented on Dockerfile
> +FROM debian:bullseye-slim
I think I'd rather have you use the latest stable. I don't think we have an advantage keeping things the same between `symbolicator` and `vroom`.

2023-07-18 14:24 UTC, aldy505 commented on Dockerfile
> +FROM debian:bullseye-slim
I'd also rather use bookworm as it has better security packages rather than bullseye (in which my highest concern is actually OpenSSL v1.1 on bullseye which [will be EOL within 1 month](https://endoflife.date/openssl)).

But considering these two things, I'd use bullseye instead:
- Other images are currently using bullseye. If we're about to use to bookworm, I'd prefer other images to migrate too.
- Do the SRE and infrastructure team at Sentry able to maintain bookworm? If they don't have the confidence to move to newer Debian release, I'd rather wait until they're confident enough.

2023-07-18 17:31 UTC, hubertdeng123 commented on Dockerfile
> +FROM debian:bullseye-slim
>  I don't think we have an advantage keeping things the same between symbolicator and vroom.

In the past, we've seen people experience some frustration around having different versions of debian for our containers. Having the same version would ease personalization as described in the issue here.
https://github.com/getsentry/self-hosted/issues/1128

2023-07-19 17:07 UTC, phacops commented on Dockerfile
> +FROM debian:bullseye-slim
I understand the frustration of the users but as it's pointed out in the issue, maybe the solution to bundle `cron` is not such a bad idea.

I don't like cross-project dependencies between projects because of another project's cleanup strategy.

2023-07-19 17:08 UTC, phacops approved these changes

2023-07-19 20:45 UTC, hubertdeng123 commented on Dockerfile
> +FROM debian:bullseye-slim
> I understand the frustration of the users but as it's pointed out in the issue, maybe the solution to bundle cron is not such a bad idea.

Yeah, you may be right. Can revisit this later

2023-07-19 20:46 UTC, merged