feat: Use pipedreams to deploy
getsentry/vroom pull request #312
Opened 2023-09-13 10:26 UTC by phacops

2023-09-13 16:28 UTC, mattgauntseo-sentry requested changes

2023-09-13 16:28 UTC, mattgauntseo-sentry commented on .github/workflows/validate-pipelines.yml
> -            - uses: getsentry/action-validate-gocd-pipelines@v1
I would recommend keeping this action since it passes the generated pipelines to the GoCD server which is the best validation we can offer at the moment.

2023-09-13 16:28 UTC, mattgauntseo-sentry commented on .github/workflows/validate-pipelines.yml
> -            - uses: getsentry/action-validate-gocd-pipelines@v1
This is my bad for not updating the docs (which I've done now) - https://www.notion.so/sentry/Pipedreams-in-GoCD-with-Jsonnet-430f46b87fa14650a80adf6708b088d9?pvs=4#517bfd0c0cd044b2a72914dcc4cb1cd9

2023-09-13 16:28 UTC, mattgauntseo-sentry commented on gocd/templates/pipelines/vroom.libsonnet
> +    GCP_PROJECT: 'internal-sentry',
It might be worth removing this here to avoid any possible mix up with the environment variables set by `eval $(/devinfra/scripts/regions/project_env_vars.py --region="${SENTRY_REGION}")`

BUT assuming you want to use the image internal-sentry for all regions, we should update the cloudbuild bash to use that value.

2023-09-13 16:28 UTC, mattgauntseo-sentry commented on gocd/templates/bash/check-cloudbuild.sh
> +	${GCP_PROJECT} \
See comment regarding GCP_PROJECT on the vroom.libsonnet file.

2023-09-13 16:28 UTC, mattgauntseo-sentry commented on gocd/templates/pipelines/vroom.libsonnet
> +      deploy_primary: {
```suggestion
      deploy-primary: {
```

The rollback pipeline is configured for `deploy-primary` stage and this matches getsentry pipelines.

2023-09-13 16:28 UTC, mattgauntseo-sentry commented on gocd/templates/vroom.jsonnet
> +  auto_deploy: true,
Optional: We default to auto-deploy, so this can be removed if you like.

2023-09-13 16:28 UTC, mattgauntseo-sentry commented on gocd/templates/pipelines/vroom.libsonnet
> +  environment_variables: {
You can add `SKIP_CANARY_CHECKS: false` here so that in the GoCD UI can change it to true for a pipeline run.

2023-09-15 08:19 UTC, phacops commented on gocd/templates/pipelines/vroom.libsonnet
> +    GCP_PROJECT: 'internal-sentry',
I remove the variable and just hard-coded the project name. I think we have to keep this image for all regions as we're not pushing it anywhere else just yet, but maybe we'll change that as we have a EU region as we might want to use a different mirror (`eu.gcr.io`vs `us.gcr.io`)?

2023-09-15 08:29 UTC, phacops commented
@mattgauntseo-sentry Do we have a way to test this? Or maybe just merging, seeing if it works and reverting is fine with GoCD?

2023-09-15 16:49 UTC, mattgauntseo-sentry commented
The Validate GoCD Pipelines is the best test we have TBH - that action sends the generated pipeline to GoCD to see if it can accept the pipeline.

There still can be some issues, but they tend to be more nuanced, and in those cases commiting and reverting is probably the easiest.

2023-09-15 16:51 UTC, mattgauntseo-sentry approved these changes

2023-09-15 16:51 UTC, mattgauntseo-sentry commented on .github/workflows/lint-deployment-pipelines.yaml
> +name: Lint Deployment Pipelines
TBH you can remove this workflow - the same step is run in the validation-pipelines workflow on line 51

2023-09-15 22:56 UTC, mattgauntseo-sentry commented on gocd/templates/jsonnetfile.json
> +      "version": "v2.2.1"
If you update this to `v2.2.2` (and run `make gocd` to update jsonnetfile.lock.json) it'll have the fix for the rollback pipeline

2023-09-18 06:55 UTC, merged